import { VStack } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { CustomInput } from '../component/Input';
import { SelectCategories } from '../component/SelectCategories';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack
        py={4}
        mx="auto"
        maxW="3xl"
        justifyContent="center"
        alignContent="center"
      >
        <SelectCategories />
        <CustomInput />
      </VStack>
    </>
  );
};

export default Home;
