import { Box, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { ListContainer } from '../component/ListTodo';
import styles from '../styles/Home.module.css';
const LIST_CATEGORIES = ['Design', 'Programming', 'Marketing', 'Finance'];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ListContainer>
        {LIST_CATEGORIES.map((val) => (
          <Box w="100%" p="4" key={val}>
            <Text>{val}</Text>
          </Box>
        ))}
      </ListContainer>
    </div>
  );
};

export default Home;
